apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui-deployment
  namespace: sotongpt
  labels:
    app: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      # main container won't start if a postgres connection cannot be made
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres-service 5432; do echo waiting; sleep 2; done;",
            ]
      containers:
        - name: openwebui
          image: ghcr.io/open-webui/open-webui:v0.8.3
          ports:
            - containerPort: 8080
          env:
            # Enable production environment, which hides the swagger docs
            - name: ENV
              value: "prod"
            - name: ENABLE_EASTER_EGGS
              value: "False"
            # Configure database connection
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            # Points to psql database
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)
            # Use pgvector for embeddings storage
            - name: VECTOR_DB
              value: pgvector
            # Improves performance of workers sharing database sessions
            - name: DATABASE_ENABLE_SESSION_SHARING
              value: "True"
            - name: CORS_ALLOW_ORIGIN
              value: "http://sotongpt.soton.ac.uk;https://sotongpt.soton.ac.uk"
            # Improves performance by only saving a complete response and by caching various parts of the chat workflow
            - name: ENABLE_REALTIME_CHAT_SAVE
              value: "False"
            - name: ENABLE_QUERIES_CACHE
              value: "True"
            - name: ENABLE_QUERIES_CACHE
              value: "True"
            - name: CHAT_RESPONSE_STREAM_DELTA_CHUNK_SIZE
              value: "7"
            # Set thread pool size for AnyIO blocking calls. If too low, the web page will become unresponsive
            - name: THREAD_POOL_SIZE
              value: "2000"
            # Higher values increase the time-to-live of a model, reducing API calls to LLMs
            - name: MODELS_CACHE_TTL
              value: "120"
            # The number of open connections to the database, both need to be kept under 100 when added together
            - name: DATABASE_POOL_SIZE
              value: "15"
            - name: DATABASE_POOL_MAX_OVERFLOW
              value: "20"
            # Disabling features which will not be used
            - name: ENABLE_AUTOCOMPLETE_GENERATION
              value: "False"
            - name: ENABLE_FOLLOW_UP_GENERATION
              value: "False"
            - name: ENABLE_IMAGE_GENERATION
              value: "False"
            - name: ENABLE_CODE_INTERPRETER
              value: "False"
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 4
              memory: 8Gi
          volumeMounts:
            - name: openwebui-storage
              mountPath: /app/backend/data
      volumes:
        - name: openwebui-storage
          persistentVolumeClaim:
            claimName: openwebui-pvc
