apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: openwebui-model-probe
  namespace: sotongpt
  labels:
    release: prometheus
spec:
  jobName: openwebui-model-probe
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://openwebui.sotongpt.svc.cluster.local:80/api/models
      labels:
        app: openwebui
  bearerTokenSecret:
    name: monitoring-secrets
    key: SOTONGPT_API_KEY
