apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-service-monitor
  namespace: sotongpt
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-collector
  endpoints:
    - port: prometheus
