apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm
  namespace: sotongpt
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: vllm-{{ .Values.model.name }}
  podMetricsEndpoints:
    - port: vllm
      path: /metrics
      interval: 5s
