apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: sotongpt
  labels:
    app: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      # main container won't start if a postgres connection cannot be made or if
      # the pipelines container isn't working
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres 5432; do echo waiting; sleep 2; done;",
            ]
      containers:
        # Core service container, which runs Open WebUI
        - name: openwebui
          image: ghcr.io/open-webui/open-webui:v0.9.6
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: redis-secret
            - secretRef:
                name: openwebui-secret
            - secretRef:
                name: hf-token-secret
            - configMapRef:
                name: openwebui
          # The env variables in here use references to secrets and other config maps
          # so have to be here. Additional env variables are in the openwebui config
          # map
          env:
            # Secret key, need to set this to coordinate replicas and muiltiple workers
            - name: WEBUI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: openwebui-secret
                  key: WEBUI_SECRET_KEY
            # Migrations should only be enabled on one replica
            - name: ENABLE_DB_MIGRATIONS
              value: "True"
            # Configure Redis connection
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: REDIS_URL
              value: redis://:$(REDIS_PASSWORD)@redis-valkey:6379/0
            - name: WEBSOCKET_REDIS_URL
              value: redis://:$(REDIS_PASSWORD)@redis-valkey:6379/1
            # Configure postgres database connection
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
          resources:
            requests:
              cpu: 4
              memory: 1Gi
            limits:
              cpu: 4
              memory: 4Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: openwebui-storage
              mountPath: /app/backend/data
        # Container where Open WebUI's pipelines run
        - name: openwebui-pipelines
          image: ghcr.io/open-webui/pipelines:git-039f9c5
          ports:
            - containerPort: 9099
          env:
            - name: GLOBAL_LOG_LEVEL
              value: DEBUG
          #   - name: PIPELINES_API_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: openwebui-secret
          #         key: PIPELINES_API_KEY
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 9099
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9099
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: pipelines-storage
              mountPath: /app/pipelines
      volumes:
        - name: openwebui-storage
          persistentVolumeClaim:
            claimName: openwebui
        - name: pipelines-storage
          persistentVolumeClaim:
            claimName: openwebui-pipelines
