apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui-deployment
  namespace: sotongpt
  labels:
    app: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      # main container won't start if a postgres connection cannot be made
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres-service 5432; do echo waiting; sleep 2; done;",
            ]
      containers:
        - name: openwebui
          image: ghcr.io/open-webui/open-webui:v0.8.3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: openwebui-config
            - secretRef:
                name: openwebui-secret
          env:
            - name: ENABLE_DB_MIGRATIONS
              value: "True"
          resources:
            requests:
              cpu: 4
              memory: 1Gi
            limits:
              cpu: 4
              memory: 4Gi
          volumeMounts:
            - name: openwebui-storage
              mountPath: /app/backend/data
      volumes:
        - name: openwebui-storage
          persistentVolumeClaim:
            claimName: openwebui-pvc
