apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-pipelines
  namespace: sotongpt
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: openwebui-pipelines
