apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui
  namespace: sotongpt
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
