apiVersion: v1
kind: Secret
metadata:
  name: openwebui-secret
  namespace: sotongpt
type: Opaque
data:
  WEBUI_SECRET_KEY: "secret-webui-key-here"
  OAUTH_CLIENT_ID: "oauth-client-id"
  OAUTH_CLIENT_SECRET: "oauth-client-secret"
