apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sotongpt-model-monitor
  namespace: sotongpt
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sotongpt-model-monitor
  endpoints:
    - port: metrics
      interval: 60s
      path: /metrics
