apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-qwen3-32b-deployment
  namespace: sotongpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-qwen3-32b-deployment
  template:
    metadata:
      labels:
        app: vllm-qwen3-32b-deployment
    spec:
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: qwen3-32b-pvc
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
      containers:
        - name: vllm
          image: vllm/vllm-openai:v0.14.1
          args:
              - abhishekchohan/Qwen3-32B-AWQ
              - --tensor-parallel-size
              - "2"
              - --gpu-memory-utilization
              - "0.90"
              - --host
              - 0.0.0.0
              - --port
              - "8000"
              - --reasoning-parser
              - qwen3
              - --kv-cache-dtype
              - fp8
              - --hf-overrides
              - '{"max_position_embeddings":131072,"rope_scaling":{"rope_type":"yarn","factor":4.0,"original_max_position_embeddings":32768}}'
              - --max-model-len
              - "131072"
          ports:
            - containerPort: 8000
          env:
            - name: VLLM_LOGGING_LEVEL
              value: INFO
            - name: VLLM_ALLOW_LONG_MAX_MODEL_LEN
              value: "1"
          resources:
            limits:
              nvidia.com/gpu: "2"
              cpu: "8"
              memory: 96Gi
            requests:
              nvidia.com/gpu: "2"
              cpu: "4"
              memory: 32Gi
          volumeMounts:
            - name: cache-volume
              mountPath: /root/.cache/huggingface
            - name: shm
              mountPath: /dev/shm
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 3
          # let's the container have 15 minutes to launch before k8s tries to
          # say that it's broken/not launching
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 180
