apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: sotongpt
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:0.15.4
          ports:
            - containerPort: 11434
          env:
            - name: CUDA_VISIBLE_DEVICES
              value: ""
            - name: OLLAMA_NUM_GPU
              value: "0"
          resources:
            requests:
              cpu: 4
              memory: 4Gi
            limits:
              cpu: 6
              memory: 8Gi
          volumeMounts:
            - name: ollama-storage
              mountPath: /root/.ollama
      volumes:
        - name: ollama-storage
          persistentVolumeClaim:
            claimName: ollama
