apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: sotongpt
  labels:
    app: postgres
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
