apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: sotongpt
spec:
  serviceName: postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg17
          args:
            - "-c"
            - "max_connections=256"
            - "-c"
            - "shared_buffers=1GB"
            - "-c"
            - "work_mem=8MB"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
              subPath: pgdata
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 4
              memory: 8Gi
  volumeClaimTemplates:
    - metadata:
        name: postgresdata
        labels:
          app: postgres
      spec:
        storageClassName: longhorn-retain
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 64Gi
