apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama
spec:
  storageClassName: manual
  claimRef:
    name: ollama
    namespace: sotongpt
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/sotongpt-data/ollama
    type: DirectoryOrCreate
