apiVersion: v1
kind: PersistentVolume
metadata:
  name: openwebui
spec:
  storageClassName: manual
  claimRef:
    name: openwebui
    namespace: sotongpt
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/sotongpt-data/openwebui-data
    type: DirectoryOrCreate
