apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
spec:
  storageClassName: local-storage
  claimRef:
    name: postgres
    namespace: sotongpt
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /opt/sotongpt-data/postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - srv04885
