apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
spec:
  storageClassName: manual
  claimRef:
    name: postgres
    namespace: sotongpt
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/sotongpt-data/postgresql
    type: DirectoryOrCreate
