apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-valkey-pv
spec:
  storageClassName: manual
  claimRef:
    name: redis-valkey-pvc
    namespace: sotongpt
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/sotongpt-data/redis-valkey
    type: DirectoryOrCreate
