apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-valkey
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /opt/sotongpt-data/redis-valkey
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - srv04885
