apiVersion: v1
kind: PersistentVolume
metadata:
  name: vllm-{{ .Values.model.name }}
spec:
  storageClassName: manual
  claimRef:
    name: vllm-{{ .Values.model.name }}
    namespace: {{ .Values.namespace }}
  capacity:
    storage: {{ .Values.resources.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.model.hostPath }}
    type: DirectoryOrCreate
