apiVersion: v1
kind: PersistentVolume
metadata:
  name: vllm-{{ .Values.model.name }}
spec:
  storageClassName: local-storage
  claimRef:
    name: vllm-{{ .Values.model.name }}
    namespace: {{ .Values.namespace }}
  capacity:
    storage: {{ .Values.resources.storage }}
  accessModes:
    - ReadWriteMany
  local:
    path: {{ .Values.model.hostPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - {{ .Values.hostNode }}
