apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-{{ .Values.model.name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: local-storage
  volumeName: vllm-{{ .Values.model.name }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.resources.storage }}
