apiVersion: v1
kind: Service
metadata:
  name: redis-valkey-service
  namespace: sotongpt
spec:
  type: ClusterIP
  selector:
    app: redis-valkey
  ports:
    - protocol: TCP
      name: redis-port
      port: 6379
      targetPort: 6379
